"""create string cache and list cache

Revision ID: 3ec8b6ba896f
Revises: 
Create Date: 2026-10-04 22:21:00.044653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ec8b6ba896f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list_cache',
    sa.Column('list_hash', sa.Uuid(), nullable=False),
    sa.Column('transformed', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('list_hash')
    )
    op.create_table('string_cache',
    sa.Column('string_hash', sa.Uuid(), nullable=False),
    sa.Column('original', sa.Text(), nullable=False),
    sa.Column('transformed_string', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('string_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('string_cache')
    op.drop_table('list_cache')
    # ### end Alembic commands ###
